apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
