apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      initContainers:
      - name: init-mysql
        image: mysql:5.7
        command:
          - "sh"
          - "-c"
          - |
            echo "Waiting for MySQL to be ready..."
            until mysqladmin ping -h mysql.fullstack-app.svc.cluster.local --silent; do
              sleep 2
            done
            echo "MySQL is ready. Creating 'todos' table..."
            mysql -h mysql.fullstack-app.svc.cluster.local -u root -p$MYSQL_ROOT_PASSWORD -D $MYSQL_DATABASE -e "
              CREATE TABLE IF NOT EXISTS todos (
                id INT AUTO_INCREMENT PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                description TEXT
              );
            "