apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: flask-app
        image: 528757829815.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5000