apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: secure-app
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dimrev/l2-py-secure-server:v0.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                key: MONGO_URI
                name: mongo-secret
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: SERVER_PORT
        ports:
        - containerPort: 5000
