apiVersion: v1
kind: ResourceQuota
metadata:
  name: multi-tier-app-quota
  namespace: multi-tier-app
spec:
  hard:
    pods: "10"
    services: "5"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "6"
    limits.memory: "12Gi"
