apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dimrev/l2-py-redis-server:v0.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_DB
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SERVER_PORT
        ports:
        - containerPort: 5000
