apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: l3-assignment
spec:
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      imagePullSecrets:
        - name: erc-secret
      containers:
      - name: worker-service
        image: <account_id>.dkr.ecr.<region>.amazonaws.com/l3-worker-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
