apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: secure-app
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # password base64 encoded
  MONGO_URI: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ286MjcwMTcvYWRtaW4= # mongodb://root:password@mongo:27017
