apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-logs-pv
  namespace: flask-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/flask-logs