apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-server-stateful
  namespace: flask-app
spec:
  serviceName: flask-server-stateful
  replicas: 2
  selector:
    matchLabels:
      app: flask-server-stateful
  template:
    metadata:
      labels:
        app: flask-server-stateful
    spec:
      containers:
      - name: flask-server-stateful
        image: dimrev/l4-flask-app:v0.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: LOG_LEVEL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
  volumeClaimTemplates:
  - metadata:
      name: logs-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
