apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: multi-tier-app
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dimrev/l2-redis-client:v0.0.2
        env:
        - name: SERVER_API_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SERVER_API_URL
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
