apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-service-manager
  namespace: secure-app
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "delete"]