apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-service-manager-binding
  namespace: secure-app
subjects:
  - kind: User
    name: PS-Manager
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-service-manager
  apiGroup: rbac.authorization.k8s.io