apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: l3-assignment
spec:
  type: LoadBalancer
  selector:
    app: web-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000